export const CustomConstants = {
  LOGIN_SCREEN: 'LoginScreen',
  SPLASH_SCREEN: 'SplashScreen',
  DASHBOARD_SCREEN: 'DashboardScreen',
  BOOTOM_TAB_NAVIGATION: 'BootomTabNavigation',
  USER_SCREEN: 'UserScreen',
  CUSTOMER_SCREEN: 'CustomerScreen',

  DASHBOARD_TABS: 'DashboardTabs',
  FLOCKS_TABS: 'FlocksTabs',

  SUPPILER_SCREEN: 'SupplierScreen',
  DASHBOARD_DETAIL_SCREEN: 'DashboardDetailScreen',

  FLOCK_SALE_SCREEN: 'FlockSaleScreen',
  FLOCKS_MORTALITY_SCREEN: 'FlocksMortalityScreen',
  FLOCKS_SCREEN: 'FlocksScreen',
  FLOCK_STOCK_SCREEN: 'FlockStockScreen',
  HOSPITALITY_SCREEN: 'HospitalityScreen',
  EGG_PRODUCTION_SCREEN: 'EggProductionScreen',
  EGG_STOCK_SCREEN: 'EggStockScreen',
  EGG_SALE_SCREEN: 'EggSaleScreen',
  MAIN_LAYOUT: 'MainLayout',
  EGG_TABS: 'EggTabs',
  POULTRY_DETAIL_TAB: 'PoultryDetailTab',
  MENU_LIST_SCREEN: 'MenuListScreen',
  SETTINGS_SCREEN: 'SettingsScreen',
  EMPLOYEE_SCREEN: 'EmployeeScreen',
  VACCINATIONS_SCREEN: 'VaccinationsScreen',
  VACCINE_SCHEDULE_SCREEN: 'VaccineScheduleScreen',
  VACCINATION_STOCK_SCREEEN: 'VaccinationStockScreen',
  SIGN_UP_SCREEN: 'SignUpScreen',
  ACCOUNT_HEAD_SCREEN: 'AccountHeadScreen',
  PAYABLES_SCREEN: 'PayablesScreen',
  LEDGER_SCREEN: 'LedgerScreen',
  RECEIVEABLES_SCREEN: "ReceivablesScreen",
  VOUCHER_SCREEN:"VoucherScreen",
FEED_RECORD_SCREEN:"FeedRecordScreen",
FEED_CONSUMPTION_SCREEN:"FeedConsumptionScreen",
FEED_STOCK_SCREEN:"FeedStockScreen",
  FLOCK_DETAIL_SCREEN: 'FlockDetailScreen',
  FLOCK_MAIN_SCREEN: 'FlockMainScreen',

  
} as const;
